# Generated by Django 3.2.25 on 2024-12-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('video_path', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
