# Generated by Django 3.2.25 on 2024-12-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
    ]
